### ISSUE TITLE
Theta X - Camera live preview not working

### ISSUE THREAD

**Issue by biviel** [ricohapi/theta-plugin-sdk#36]
I was able to start camera on Theta X and to get the live preview the same way as doing at Z1:

![image](https://user-images.githubusercontent.com/93625553/157015250-eda6b264-3da0-4e13-8d3e-6849b5d680a4.png)

parms.set(“RIC_SHOOTING_MODE”, “RicPreview3840”);
parms.set(“RIC_PROC_STITCHING”, “RicStaticStitching”);

Issues:

1. Stitching doesn’t work even if I set as above, I tried all valid values from documentation but couldn't turn on stitching for live preview.
2. During preview like I get only one of the lenses preview, when I try to set preview size parms.setPreviewSize(3840, 1920); plugin fails, when I try to check supported preview sizes I get supported size: 1920 x 1920, 1920 x 1440, 1920 x 1080 , no higher resolutions

Error msg in logcat:
E/AndroidRuntime: FATAL EXCEPTION: RenderThread
    Process: tours.flow.hdrstreaming, PID: 7215
    java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2234)
        at tours.flow.hdrstreaming.e.j.n(:253)
        at tours.flow.hdrstreaming.e.j.e(:51)
        at tours.flow.hdrstreaming.e.m$a.run(:115)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at tours.flow.hdrstreaming.e.m.m(:97)
        at tours.flow.hdrstreaming.e.m.n(Unknown Source:0)
        at tours.flow.hdrstreaming.e.e.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:919)

3. Exposure compensation is bad in some cases image is overexposure a lot, seems randomly changes after starting and stopping multiple times the plugin.

I'm using plugin library 3.0.1 in my plugin.

A sample live streaming app/plugin would help a lot to make this work ASAP!

Thanks!

**Comment by DaisukeHohjoh** [comment]
Dear @biviel ,

We appreciate your input and apologize for the lack of updates.
As there hasn't been any activity on this issue for a prolonged period, we will be closing it for now.
Should you have further questions or if the issue persists, please don't hesitate to reopen or comment.

As for now, please refer to following repository for Theta X Camera API usage.
https://github.com/ricohapi/theta-plugin-camera-api-sample-x

Best Regards,
Daisuke Hohjoh
